### ISSUE TITLE
在CatServer 1.12.2服务端上无法运行

### ISSUE THREAD

**Issue by zxc7895531** [FastScriptModule/FastScript#1]
错误信息：https://paste.ubuntu.com/p/djm7fnxfX3/
使用MCBBS宣传贴中的getPlayerInfo示例脚本，无法eval也无法run

**Comment by zxc7895531** [comment]
在Paper以及石墨端中也无法运行，报错如出一辙，服务器核心均采用能下载到的最新版

**Comment by Score2** [comment]
Try to use new release: https://github.com/FastScriptModule/FastScript/releases/tag/1.0.4-SNAPSHOT
