### ISSUE TITLE
执行fs reload后无法执行新添加的脚本

### ISSUE THREAD

**Issue by zxc7895531** [FastScriptModule/FastScript#2]
执行fs reload后无法执行新添加的脚本，如果将已存在脚本重命名也无法使用

**Comment by Score2** [comment]
paper端无法复现该错误，有无相关错误的抛出？如有，请提供。抱歉，我没有更多资源去使用catserver复现该错误。

**Comment by Score2** [comment]
Try to use new release: https://github.com/FastScriptModule/FastScript/releases/tag/1.0.4-SNAPSHOT
